테스트

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -2,9 +2,9 @@ name: CI for main
 
 on:
   push:
-    branches: [ main ]
+    branches: [ test-workflow ]
   pull_request:
-    branches: [ main ]
+    branches: [ test-workflow ]
 
 jobs:
   checking-code-format:
@@ -16,276 +16,24 @@ jobs:
           - check: 'mod'
             exclude: '(leafLowparser|leafLowscanner|lowparser|lowscanner)'
     steps:
-    - uses: actions/checkout@v4
-    - name: run clang-format to verify current codes.
-      uses: jidicula/clang-format-action@v4.13.0
-      with:
-        clang-format-version: '18'
-        check-path: ${{ matrix.path['check'] }}
-        exclude-regex: ${{ matrix.path['exclude'] }}
+    - name: checkout repository codes
+      uses: actions/checkout@v4
 
-  build-on-linux:
-    needs: [checking-code-format]
-    name: build on linux
-    runs-on: ubuntu-22.04
-
-    steps:
-    - name: install native dependencies.
+    - name: Install clang-format-18
       run: |
-        sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz clang clang-format clang-tidy
-        ls .
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make
-        sudo make install
-        cd ..
-        sudo rm -rf bison-3.8.2
-        if [ -f /usr/bin/bison ]; then
-          sudo mv /usr/bin/bison /usr/bin/bison-prev
+        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
+        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
+        sudo apt update
+        sudo apt install -y clang-format-18
+
+    - name: run clang-format
+      run: |
+        git clang-format-18 --diff --binary clang-format-18 HEAD^ --extensions c,cpp,h,hpp,inl > clang-format.diff
+
+    - name: check formatting
+      run: |
+        if [ -s clang-format.diff ]; then
+          echo "error: clang-format check failure."
+          cat clang-format.diff
+          exit 1
         fi
-        sudo ln -s /usr/local/bin/bison /usr/bin/bison
-
-    - name: checkout repository codes
-      uses: actions/checkout@v2
-
-    - name: build in release mode & test current codes.
-      run: |
-        export C=clang CXX=clang++ PYTHON=$(which python3)
-        ls -l ${{github.workspace}}/mod/leaf/parser/bison
-        sudo $PYTHON ${{github.workspace}}/build/builder.py pub deb
-        sudo $PYTHON ${{github.workspace}}/build/builder.py test
-
-    - name: upload output files.
-      uses: actions/upload-artifact@v4
-      with:
-        name: namu-ubuntu-x64
-        path: ${{github.workspace}}/bin/namu-ubuntu-x64.deb
-
-  build-for-wasm:
-    needs: [checking-code-format]
-    name: build for wasm
-    runs-on: ubuntu-22.04
-
-    steps:
-    - name: checkout repository codes
-      uses: actions/checkout@v2
-
-    - name: install native dependencies.
-      run: |
-        sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz clang clang-format clang-tidy
-        ls .
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make
-        sudo make install
-        cd ..
-        echo $(which bison)
-        sudo rm -rf bison-3.8.2
-        if [ -f /usr/bin/bison ]; then
-          sudo mv /usr/bin/bison /usr/bin/bison-prev
-        fi
-        sudo ln -s /usr/local/bin/bison /usr/bin/bison
-
-    - name: install emscripten librires
-      uses: mymindstorm/setup-emsdk@v14
-
-    - name: verify emscripten
-      run: |
-        echo $(which emcc)
-        emcc -v
-
-    - name: build wasm
-      run: |
-        export C=clang CXX=clang++ PYTHON=$(which python3)
-        ls -l ${{github.workspace}}/mod/leaf/parser
-        export PATH="$(dirname $(which emmake)):$PATH"
-        $PYTHON ${{github.workspace}}/build/builder.py wasm
-
-    - name: upload wasm file
-      uses: actions/upload-artifact@v4
-      with:
-        name: namu-wasm
-        path: |
-          ${{github.workspace}}/bin/namu.js
-          ${{github.workspace}}/bin/namu.wasm
-
-  measure-coverage:
-    needs: [build-on-linux]
-    name: measure code coverage
-    runs-on: ubuntu-22.04
-
-    steps:
-    - name: install native dependencies
-      run: |
-        sudo apt-get update
-        sudo apt install -y python3 python3-pip cmake wget flex graphviz clang-format clang-tidy llvm lcov
-        ls .
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make
-        sudo make install
-        cd ..
-        sudo rm -rf bison-3.8.2
-        sudo mv /usr/bin/bison /usr/bin/bison-prev
-        sudo ln -s /usr/local/bin/bison /usr/bin/bison
-
-    - name: checkout repository codes.
-      uses: actions/checkout@v2
-
-    - name: build for measuring coverage
-      run: |
-        export C=clang CXX=clang++ PYTHON=$(which python3)
-        sudo $PYTHON ${{github.workspace}}/build/builder.py cov
-
-    - name: upload coverage report to codecov
-      uses: codecov/codecov-action@v4.0.1
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
-        files: ./build/cov.info
-
-  build-on-macos:
-    needs: [checking-code-format]
-    name: build on macos
-    runs-on: macos-15
-
-    steps:
-    - name: checkout repository codes
-      uses: actions/checkout@v2
-
-    - name: install native dependencies.
-      run: |
-        brew unlink python && brew link --overwrite python
-        brew install cmake wget bison flex graphviz llvm
-        ln -s "/opt/homebrew/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"
-        ln -s "/opt/homebrew/opt/llvm/bin/clang-format" "/usr/local/bin/clang-format"
-
-        echo "install bison"
-        sudo wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz
-        tar -zxvf bison-3.8.2.tar.gz
-        cd bison-3.8.2
-        ./configure
-        sudo make
-        sudo make install
-        cd ..
-
-    - name: build in release mode & test current codes.
-      run: |
-        export PATH="/usr/local/bin:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
-        export C=clang CXX=clang++ PYTHON=$(which python3)
-        ls -l ${{github.workspace}}/mod/leaf/parser/bison
-        $PYTHON ${{github.workspace}}/build/builder.py pub mac
-        $PYTHON ${{github.workspace}}/build/builder.py test
-
-    - name: archive to tar files
-      run: tar -cvf namu-macos-x64.tar ${{github.workspace}}/bin/
-
-    - name: upload output files.
-      uses: actions/upload-artifact@v4
-      with:
-        name: namu-macos-x64
-        path: namu-macos-x64.tar
-
-  build-on-windows:
-    needs: [checking-code-format]
-    name: build on windows
-    runs-on: windows-latest
-
-    steps:
-    - name: checkout repository codes
-      uses: actions/checkout@v2
-
-    - name: Add msbuild to PATH
-      uses: microsoft/setup-msbuild@v1.1
-
-    - name: install apps from choco
-      uses: crazy-max/ghaction-chocolatey@v2.0.0
-      with:
-        args: install -y wget unzip zip
-
-    - name: get flex_bison for windows & unzip
-      run: |
-        mkdir ${{github.workspace}}\flex_bison
-        wget -O flex_bison\flex_bison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip
-        cd flex_bison
-        unzip flex_bison.zip
-        ren win_flex.exe flex.exe
-        ren win_bison.exe bison.exe
-
-    - name: build in release mode
-      run: |
-        $env:PATH = "$env:PATH;${{github.workspace}}\flex_bison"
-        python ${{github.workspace}}\build\builder.py pub win
-
-    - name: archives to zip file
-      run: |
-        zip -9vr namu-win-x64-portable.zip ${{github.workspace}}\bin
-
-    - name: upload output files.
-      uses: actions/upload-artifact@v4
-      with:
-        name: namu-win-x64-portable
-        path: namu-win-x64-portable.zip
-
-    - name: get advanced installer
-      uses: caphyon/advinst-github-action@v2.0
-      with:
-        # advinst-license:
-        advinst-enable-automation: 'true'
-
-    - name: build msi installer
-      shell: pwsh
-      run: |
-        $aipPath = "${{github.workspace}}\.github\workflows\namu.aip";
-        Write-Host "AIP: $aipPath";
-        $advinst = new-object -com advancedinstaller;
-        $project = $advinst.LoadProject($aipPath);
-        $productDetails = $project.ProductDetails;
-        $productDetails.Version = $(python ${{github.workspace}}\build\builder.py ver)
-        Write-Host "Version: $productDetails.Version";
-        $project.Build();
-
-    - name: upload msi file
-      uses: actions/upload-artifact@v4
-      with:
-        name: namu-win-x64
-        path: ${{github.workspace}}\.github\workflows\namu-win-x64.msi
-
-  publish-doc:
-    needs: [build-on-linux, build-on-macos, build-on-windows, build-for-wasm]
-    name: publish doc
-    runs-on: ubuntu-22.04
-
-    steps:
-      - name: install native dependencies.
-        run: |
-          sudo apt install -y doxygen graphviz python3 python3-pip ruby rubygems
-
-      - name: install python dependencies.
-        run: sudo python3 -m pip install --upgrade jinja2 Pygments
-
-      - name: install gems.
-        run: sudo gem install jekyll bundler
-
-      - name: checkout master codes.
-        uses: actions/checkout@v2
-
-      - name: commit docs if it's different to previous commit
-        run: |
-          export C=clang CXX=clang++ PYTHON=$(which python3)
-          sudo $PYTHON ${{github.workspace}}/build/builder.py doc
-          sudo $PYTHON ${{github.workspace}}/build/builder.py pubdoc
-
-      - name: push the commit
-        uses: ad-m/github-push-action@v0.6.0
-        with:
-          directory: ${{github.workspace}}/build/html
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          branch: 'gh-pages'
